name: Esempio di Workflow Meteo

on:
  push:
    branches: [ main ]

jobs:
  weather_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get Weather
      run: |
        curl "http://api.weatherapi.com/v1/current.json?key=${{ secrets.WEATHER_API }}&q=London"
      env:
        WEATHER_API: ${{ secrets.WEATHER_API }}
